version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "deps(python)"
    reviewers:
      - "wild8highlander"

  - package-ecosystem: "npm"
    directory: "/interactive-viz"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "web-app"
    commit-message:
      prefix: "deps(npm)"
    reviewers:
      - "wild8highlander"

  - package-ecosystem: "maven"
    directory: "/java-webapp"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "java"
    commit-message:
      prefix: "deps(maven)"
    reviewers:
      - "wild8highlander"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "deps(actions)"
