#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Двуязычные подписи для фигур экспериментов (RU/EN)."""

L = {
    "ru": {
        # --- Эксперимент 1 (Ш.3) ---
        "floor": "Матричный пол (теорема)",
        "tree_weighted": "Взвешенное дерево Кунца (минимум)",
        "permutation": "Перестановочные модели",
        "tree_trunc": "Обрезка дерева Кунца",
        "e_xlabel": "Дефект на душу размерности  e = F/n",
        "e_title": "Эксперимент 1: лестница препятствий моста Ш.3(iii)",
        "e_observed": "e(ε) — естественный перенос X_i = √(4/7)·P_i",
        "floor_label": "острый пол 5/7 (теорема следа)",
        "hamming_eps": "— доля неподвижных точек (ошибка Хэмминга)",
        "e_ylabel": "e = F/n",
        "hamming_title": "Эксперимент 1G: софические данные — дефект не убывает с ε",
        # --- Эксперимент 2 (DSI-4) ---
        "cand_title": "Эксперимент 2: структурные кандидаты амплитуды c_K3",
        "cand_ylabel": "Отклонение от измеренного c_K3 = 0.040177576, %",
        "cand_xlabel": "Кандидат",
        "conv_title": "Эксперимент 2: подходящие дроби c_K3 (девиация от измеренного)",
        "conv_xlabel": "Знаменатель q подходящей дроби p/q",
        "conv_ylabel": "|p/q − c_K3| (абс.)",
        "conv_9_224": "9/224 = 27/672",
        # --- Эксперимент 3 (Гурвица) ---
        "tower_title": "Эксперимент 3: башня Гурвица — торможение δ_eff = δ⁵/b₂",
        "tower_xlabel": "Род поверхности g",
        "tower_ylabel": "δ_eff (лог. шкала)",
        "tower_klein": "Клейн (2,3,7)",
        "tower_macbeath": "Макбит (2,3,9)",
        "tower_psl213": "PSL(2,13) (2,3,13)",
        "tower_triplet": "триплет Гурвица (2,3,8)",
        "gamma_title": "Эксперимент 3: коэффициент торможения γ = δ⁴/b₂",
        "gamma_ylabel": "γ (лог. шкала)",
        # --- Эксперимент 4 (QNM) ---
        "qnm_title": "Эксперимент 4: предсказанные сдвиги QNM Δf = −8.4·10⁻⁵·f",
        "qnm_xlabel": "Событие",
        "qnm_ylabel": "Δf, Гц",
        "qnm_detect_title": "Эксперимент 4: отношение |Δf|/σ (обнаружимость)",
        "qnm_detect_ylabel": "|Δf| / σ",
        "qnm_overtones_title": "Эксперимент 4: лестница обертонов GW150914 (l=m=2, предел Шварцшильда, M_f = 62.3 M☉)",
        "qnm_overtones_xlabel": "Номер обертона n",
        "qnm_overtones_ylabel": "f_n, Гц",
        "qnm_shift": "сдвиг Δf_n",
        # --- Эксперимент 5 (QCD) ---
        "nscaling_title": "Эксперимент 5: N-scaling |⟨λ⟩| — проверка θ̄_artifact ~ 1/√N",
        "nscaling_xlabel": "N (размерность, лог. шкала)",
        "nscaling_ylabel": "|⟨λ⟩| (лог. шкала)",
        "nscaling_data": "|⟨λ⟩| (M усреднений)",
        "nscaling_floor": "пол σ/√(MN)",
        "nscaling_sqrt": "наклон 1/√N",
        "kappa_title": "Эксперимент 5: κ_T-sweep — байес-фактор BF(GUE/Poisson)",
        "kappa_xlabel": "κ_T",
        "kappa_ylabel": "BF(GUE/Poisson) (лог. шкала)",
        "kappa_262": "решёточный κ_T > 2.62 (95% CL)",
        # --- Эксперимент 6 (224 = 4·56) ---
        "scan_title": "Эксперимент 6: переписной фильтр — знаменатели 2^a·3^b·7^c\n(a≤6, b≤1, c≤1), q ≤ 5000, числитель p ≤ 32",
        "scan_xlabel": "Знаменатель q (лог. шкала)",
        "scan_ylabel": "|p/q − c_K3| (абс., лог. шкала)",
        "scan_census": "переписные дроби {7,3}",
        "scan_junk": "прочие дроби p/q",
        "scan_9_224": "9/224 = 27/672",
        "scan_band": "полоса 0.1%",
        "genus_title": "Эксперимент 6: родовое семейство амплитуды c(g) — ветви механизмов",
        "genus_xlabel": "Род g (башня Гурвица)",
        "genus_ylabel": "c(g) (лог. шкала)",
        "genus_branch1": "ветвь I: 27/(4|G|) = 9/(4V)  ~ (g−1)⁻¹",
        "genus_branch2": "ветвь II: (N−1)/(FN)  ~ (g−1)⁻¹·(1−1/N)",
        "genus_branch3": "ветвь III (фреймворк): b_Ch(b₂)  ~ (g−1)⁻²",
        "genus_deg": "вырождение I = II — только g = 3",
        # --- Эксперимент 7 (порог e ≥ 1) ---
        "ladder2_title": "Эксперимент 7: лестница становится теоремой — класс носитель-изометрических пар",
        "ladder2_xlabel": "Дефект на душу e = F/n",
        "lab_free": "Свободные скаляры √(4/7)·I (вне класса)",
        "lab_pi": "Частичные изометрии — ПОРОГ e ≥ 1 (теорема A)",
        "lab_tree": "Обрезка дерева: e = 1 + 2/n (теорема B)",
        "lab_unitary": "Унитарные/перестановочные пары: e = 2 (теорема C)",
        "tree_line_title": "Эксперимент 7: точная арифметика покрытия F = n + 2·rank(R)",
        "tree_line_xlabel": "Глубина обрезки k  (n = 2^(k+1) − 1)",
        "tree_line_ylabel": "F",
        "tree_exact": "обрезка дерева: F = n+2 (теорема B)",
        "floor_n": "пол класса: F = n (e = 1)",
        "unit_line": "унитарные пары: F = 2n",
        # --- Фигура Чоптюка ---
        "ch_title": "Задача Чоптюка: универсальный массовый скейлинг (иллюстрация)",
        "ch_xlabel": "ln(p − p*)",
        "ch_ylabel": "ln M_BH",
        "ch_slope": "наклон γ ≈ 0.374",
        "ch_fam1": "семейство данных A",
        "ch_fam2": "семейство данных B",
        "ch_const_title": "Критический показатель: измерение против кандидата фреймворка",
        "ch_gamma": "γ Чоптюка ≈ 0.374 (универсальна)",
        "ch_bch": "b_Ch = 1−cos(2π/7) ≈ 0.3765",
        "ch_inv": "1/λ₀ ≈ 0.374 (одна неустойчивая мода)",
    },
    "en": {
        # --- Experiment 1 (Sh.3) ---
        "floor": "Matrix floor (theorem)",
        "tree_weighted": "Weighted Cuntz tree (minimum)",
        "permutation": "Permutation models",
        "tree_trunc": "Cuntz-tree truncation",
        "e_xlabel": "Per-dimension defect  e = F/n",
        "e_title": "Experiment 1: obstruction ladder of the Sh.3(iii) bridge",
        "e_observed": "e(ε) — natural transfer X_i = √(4/7)·P_i",
        "floor_label": "sharp floor 5/7 (trace theorem)",
        "hamming_eps": "— fixed-point fraction (Hamming error)",
        "e_ylabel": "e = F/n",
        "hamming_title": "Experiment 1G: sofic data — defect does not decay with ε",
        # --- Experiment 2 (DSI-4) ---
        "cand_title": "Experiment 2: structural candidates for the c_K3 amplitude",
        "cand_ylabel": "Deviation from measured c_K3 = 0.040177576, %",
        "cand_xlabel": "Candidate",
        "conv_title": "Experiment 2: continued-fraction convergents of c_K3",
        "conv_xlabel": "Convergent denominator q (p/q)",
        "conv_ylabel": "|p/q − c_K3| (abs.)",
        "conv_9_224": "9/224 = 27/672",
        # --- Experiment 3 (Hurwitz) ---
        "tower_title": "Experiment 3: Hurwitz tower — braking δ_eff = δ⁵/b₂",
        "tower_xlabel": "Surface genus g",
        "tower_ylabel": "δ_eff (log scale)",
        "tower_klein": "Klein (2,3,7)",
        "tower_macbeath": "Macbeath (2,3,9)",
        "tower_psl213": "PSL(2,13) (2,3,13)",
        "tower_triplet": "Hurwitz triplet (2,3,8)",
        "gamma_title": "Experiment 3: braking coefficient γ = δ⁴/b₂",
        "gamma_ylabel": "γ (log scale)",
        # --- Experiment 4 (QNM) ---
        "qnm_title": "Experiment 4: predicted QNM shifts Δf = −8.4·10⁻⁵·f",
        "qnm_xlabel": "Event",
        "qnm_ylabel": "Δf, Hz",
        "qnm_detect_title": "Experiment 4: |Δf|/σ ratio (detectability)",
        "qnm_detect_ylabel": "|Δf| / σ",
        "qnm_overtones_title": "Experiment 4: GW150914 overtone ladder (l=m=2, Schwarzschild limit, M_f = 62.3 M☉)",
        "qnm_overtones_xlabel": "Overtone number n",
        "qnm_overtones_ylabel": "f_n, Hz",
        "qnm_shift": "shift Δf_n",
        # --- Experiment 5 (QCD) ---
        "nscaling_title": "Experiment 5: N-scaling of |⟨λ⟩| — testing θ̄_artifact ~ 1/√N",
        "nscaling_xlabel": "N (dimension, log scale)",
        "nscaling_ylabel": "|⟨λ⟩| (log scale)",
        "nscaling_data": "|⟨λ⟩| (M averages)",
        "nscaling_floor": "floor σ/√(MN)",
        "nscaling_sqrt": "slope 1/√N",
        "kappa_title": "Experiment 5: κ_T sweep — Bayes factor BF(GUE/Poisson)",
        "kappa_xlabel": "κ_T",
        "kappa_ylabel": "BF(GUE/Poisson) (log scale)",
        "kappa_262": "lattice κ_T > 2.62 (95% CL)",
        # --- Experiment 6 (224 = 4·56) ---
        "scan_title": "Experiment 6: census filter — denominators 2^a·3^b·7^c\n(a≤6, b≤1, c≤1), q ≤ 5000, numerator p ≤ 32",
        "scan_xlabel": "Denominator q (log scale)",
        "scan_ylabel": "|p/q − c_K3| (abs., log scale)",
        "scan_census": "census fractions of {7,3}",
        "scan_junk": "other fractions p/q",
        "scan_9_224": "9/224 = 27/672",
        "scan_band": "0.1% band",
        "genus_title": "Experiment 6: genus family of the amplitude c(g) — mechanism branches",
        "genus_xlabel": "Genus g (Hurwitz tower)",
        "genus_ylabel": "c(g) (log scale)",
        "genus_branch1": "branch I: 27/(4|G|) = 9/(4V)  ~ (g−1)⁻¹",
        "genus_branch2": "branch II: (N−1)/(FN)  ~ (g−1)⁻¹·(1−1/N)",
        "genus_branch3": "branch III (framework): b_Ch(b₂)  ~ (g−1)⁻²",
        "genus_deg": "degeneracy I = II — only g = 3",
        # --- Experiment 7 (e ≥ 1 threshold) ---
        "ladder2_title": "Experiment 7: the ladder becomes a theorem — carrier-isometric class",
        "ladder2_xlabel": "Per-dimension defect e = F/n",
        "lab_free": "Free scalars √(4/7)·I (outside the class)",
        "lab_pi": "Partial isometries — THRESHOLD e ≥ 1 (Theorem A)",
        "lab_tree": "Tree truncation: e = 1 + 2/n (Theorem B)",
        "lab_unitary": "Unitary/permutation pairs: e = 2 (Theorem C)",
        "tree_line_title": "Experiment 7: exact covering arithmetic F = n + 2·rank(R)",
        "tree_line_xlabel": "Truncation depth k  (n = 2^(k+1) − 1)",
        "tree_line_ylabel": "F",
        "tree_exact": "tree truncation: F = n+2 (Theorem B)",
        "floor_n": "class floor: F = n (e = 1)",
        "unit_line": "unitary pairs: F = 2n",
        # --- Choptuik figure ---
        "ch_title": "The Choptuik problem: universal mass scaling (illustration)",
        "ch_xlabel": "ln(p − p*)",
        "ch_ylabel": "ln M_BH",
        "ch_slope": "slope γ ≈ 0.374",
        "ch_fam1": "data family A",
        "ch_fam2": "data family B",
        "ch_const_title": "Critical exponent: measurement vs framework candidate",
        "ch_gamma": "Choptuik γ ≈ 0.374 (universal)",
        "ch_bch": "b_Ch = 1−cos(2π/7) ≈ 0.3765",
        "ch_inv": "1/λ₀ ≈ 0.374 (single unstable mode)",
    },
}
